apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: wikijs  
  labels:
    app: wikijs
data:
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_TYPE: "postgres"
  DB_NAME: "wiki"
