apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wikijs
  name: wikijs
  namespace: wikijs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wikijs 
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - name: wikijs
        image: requarks/wiki:2
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: postgres-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: postgres-config
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: postgres-config
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              key: DB_TYPE
              name: postgres-config
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: postgres-config
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
          - mountPath: /opt/wikijs
            name: wikijs-stg
      volumes:
        - name: wikijs-stg
          persistentVolumeClaim: 
            claimName: wikijs-pvc
