apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  namespace: wikijs
  labels:
    type: local
    app: postgres
spec:
  storageClassName: postgres-data
  accessModes:
    - ReadWriteOnce
  capacity: 
    storage: 5Gi
  hostPath:
    path: /data/pv001

