kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: wikijs
  labels:
    app: postgres
spec:
#  storageClassName: postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

